### PR TITLE
Add additional swiping info to cardBuilder callback and add an additional callback containing the horizontal and vertical swipe direction

### LINKED ISSUE #21: Add overlay builder with direction and progress
Hello, appreciate your work with this package, especially considering that Appinio Swiper is basically abandoned. I was wondered if it would be possible to add an overlay builder, so that it would be possible to create animated overlays, like Tinder which displays a "Like" or "Nope" text in the corner, when the user swipes (see https://www.virtuallocation.com/images/tinder/tinder-swipe-3.jpg). 

Ideally this builder would be a method, that gives the direction the user has swiped, as well as the progress of how fair they've swiped the card from the center. The method would return a widget, that would be drawn ontop of the top card (the one being dragged). The progress would be used to fade in or out the overlay depending on how far the user drags the card, and the direction would be used for showing different overlays, depending on which direction the user drags the card.

The package swipable_stack has this feature, if that is of any help: https://pub.dev/packages/swipable_stack

Thanks again for your work, this package definitely seems like the best and most elegant swipe solution for Flutter.

### PR DESCRIPTION
**Pull request by sarope**
## Description

- Adds `onSwipeDirectionChange` callback containing the horizontal and vertical swipe direction
- Modifies the `cardBuilder` callback to include the ratio of vertical drag to threshold as a percentage
  and the ratio of horizontal drag to threshold as a percentage.

## Related Issues

- Closes #21 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/ricardodalarme/flutter_card_swiper/blob/main/CONTRIBUTING.md
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/ricardodalarme/flutter_card_swiper/blob/chore/add-a-contributing-guide/CONTRIBUTING.md#version
[following repository CHANGELOG style]:https://github.com/ricardodalarme/flutter_card_swiper/blob/chore/add-a-contributing-guide/CONTRIBUTING.md#changelog

### CODE REVIEW

**Comment by sarope** [comment]
Hey @ricardodalarme. Thanks for maintaining this package 👍 Is there anything else you need from me to get this merged in?

**Comment by shakilurPolygon** [comment]
onEnd is not working in this commit. Has anyone faced this issue?

**Comment by nejedlypetr** [comment]
Love this PR! I am excited about merging. Thank you both @ricardodalarme @sarope

**Review by ricardodalarme — APPROVED** [review]

**Comment by ZhiaDev** [comment]
Can anyone give an example of how to use onSwipeDirectionChange to show like or Nope badges on cards

**Pull request merged**
